vippsas/vipps-magento

Model/OrderPlace.php

- Fixed undefined Index for Website level configuration
- Fixed callback processing for canceled orders.

VIPPS-147: Publication 1.0.4

---

Cron/FetchOrderFromVipps.php
Model/OrderPlace.php
Model/TokenProvider.php
Plugin/Config/Model/Config.php
etc/adminhtml/system.xml

- Fixed GitHub issue https://github.com/vippsas/vipps-magento/issues/9
- Improved order processing by cron job
- Added amount validation when order placing by cron
- Moved Vipps configuration from PayPal section

Vipps Publication v.1.0.6

---

Controller/Payment/ConsentRemoval.php
Cron/FetchOrderFromVipps.php
Gateway/Command/CaptureCommand.php
Gateway/Command/RefundCommand.php
Gateway/Exception/ExceptionFactory.php
Gateway/Http/Client/Curl.php
Gateway/Request/Initiate/MerchantDataBuilder.php
Gateway/Request/TransactionDataBuilder.php
Jenkinsfile
Model/OrderPlace.php
Model/Profiling/Profiler.php
Model/TokenProvider.php
Plugin/Config/Model/Config.php
Setup/UpgradeSchema.php
composer.json
etc/adminhtml/system.xml
etc/adminhtml/system/express_checkout.xml

- Moved configurations from website level to store level (VIPPS-157)
- Added mandatory parameter "consentRemovalPrefix" during initiate payment request (VIPPS-161)
- Improved JWT token regeneration process (VIPPS-158)
- Improved background processor (VIPPS-162)
- Fixed issue with round of amount (VIPPS-163)

VIPPS-164: Publication v.1.0.9

---

.gitignore
Controller/Payment/Express.php
Controller/Payment/Fallback.php
Controller/Payment/Regular.php
Cron/FetchOrderFromVipps.php
Gateway/Exception/ExceptionFactory.php
Gateway/Request/Initiate/InitiateBuilderInterface.php
Gateway/Request/Initiate/MerchantDataBuilder.php
Gateway/Request/Initiate/TransactionDataBuilder.php
Gateway/Request/TransactionTextDataBuilder.php
Model/LockManager.php
Model/OrderPlace.php
Model/TokenProvider.php
Setup/UpgradeSchema.php
Test/Unit/Model/TokenProviderTest.php
etc/di.xml
phpcs.xml
phpmd.xml
phpunit.xml

- Fixed issue when error occurred "Reserved amount in Vipps is not the same as order amount" (VIPPS-165)

VIPPS-166: Publication v.1.0.10

---

Gateway/Command/CaptureCommand.php
Gateway/Command/RefundCommand.php
Gateway/Config/Config.php
composer.json
etc/adminhtml/di.xml
etc/di.xml
etc/frontend/di.xml

- Fixed issue of background processing when module installed not in default scope

VIPPS-167: Publication v.1.0.11

---

Controller/Payment/Callback.php
Controller/Payment/Fallback.php
Controller/Payment/ShippingDetails.php
Cron/FetchOrderFromVipps.php
Gateway/Exception/ExceptionFactory.php
Gateway/Exception/WrongAmountException.php
Gateway/Response/InitiateHandler.php
Model/Gdpr/Compliance.php
Model/OrderPlace.php
Model/Profiling/Profiler.php
Model/Quote/AddressUpdater.php
Model/QuoteUpdater.php
composer.json
etc/adminhtml/system.xml
etc/di.xml

- Added GDPR compliance processor (VIPPS-168)
- Fixed issue when not all customer information comes from Vipps gateway (VIPPS-170)
- Added support of "Authorize and Capture" behavior (VIPPS-170)
- Fixed issue when catalog price rules not applied during background processing

VIPPS-172: Publication v.1.0.12

---

Api/CommandManagerInterface.php
Controller/Payment/Callback.php
Cron/FetchOrderFromVipps.php
Gateway/Command/CommandManager.php
Gateway/Transaction/Transaction.php
Model/OrderPlace.php
Model/QuoteUpdater.php
composer.json

- Background process improvements
-- all quotes have 3 attempts to be placed, then will be canceled
-- in case of quote cancelation (error occurred or time out) reserved amount in Vipps will be released

VIPPS-173: Publication v.1.0.13

---

Api/Profiling/Data/ItemInterface.php
Cron/FetchOrderFromVipps.php
Gateway/Command/GatewayCommand.php
Gateway/Http/Client/Curl.php
Gateway/Transaction/Transaction.php
INSTALL.md
Model/Profiling/Item.php
Model/Profiling/Profiler.php
Model/Profiling/ProfilerInterface.php
composer.json
etc/di.xml

- Fixed issue with incorrect statuses displayed on monitoring grid
- Fixed issue with profiler save process when transaction rolled back

VIPPS-193: Publication v.1.2.2

---

Gateway/Command/CaptureCommand.php
Gateway/Command/RefundCommand.php
Gateway/Http/Client/Curl.php
Gateway/Http/TransferFactory.php
Gateway/Request/Initiate/TransactionDataBuilder.php
Gateway/Request/TransactionDataBuilder.php
Model/OrderPlace.php
composer.json

- Compatibility with Magento 2.3

Publication 1.3.1

---

Gateway/Command/CaptureCommand.php
Model/OrderPlace.php
composer.json
etc/adminhtml/system.xml
etc/config.xml
etc/di.xml

Refactor authorize/capture commands to be more compliant with payment logic.

VIPPS-221: Publication 1.2.5

---

composer.json
view/adminhtml/templates/monitoring/view.phtml

VIPPS-222: Publication 1.2.6

---

Model/Order/Cancellation/Config.php
Setup/Uninstall.php
composer.json
etc/adminhtml/system.xml
etc/adminhtml/system/cancellation.xml
etc/config.xml
view/adminhtml/templates/monitoring/view.phtml

- Create Uninstall script.
- Simplify cancellation config path.

Publication 1.2.7

---

Gateway/Response/TransactionHandler.php
Model/Order/Cancellation/Config.php
Model/OrderPlace.php
README.md
Setup/Uninstall.php
composer.json
etc/adminhtml/system.xml
etc/adminhtml/system/cancellation.xml
etc/config.xml
view/adminhtml/templates/monitoring/view.phtml

Fix transaction handler.
Update configuration.

Publication 1.3.6

---

Model/TransactionProcessor.php
Observer/CheckoutSubmitAllAfter.php
Plugin/Sales/OrderManagement/AfterPlaceOrder.php
composer.json
etc/frontend/di.xml
etc/webapi_rest/di.xml

- order confirmation email sent after payment has been approved

VIPPS-299: Order Confirmation email

---

Block/Adminhtml/Order/View/Info/PaymentInfo.php
composer.json

- fixed issue with  undefined method type on order view page.

Vipps Publication 2.3.5

---

Observer/CheckoutSubmitAllAfter.php
composer.json

- fixed issue with multi-shipping checkout

Vipps Publication 2.3.6

---

i18n/nb_NO.csv

Fixed typo in "Your order was cancelled in Vipps.".

---

Controller/Payment/Fallback.php
Model/Exception/AcquireLockException.php
Model/TransactionProcessor.php
composer.json

- removed showing exception to enduser

Publication 2.3.7

---

Controller/Payment/Fallback.php
Gateway/Transaction/Transaction.php
composer.json

- Fixed issue with captured transaction on Fallback

Fixed issue with captured transaction on Fallback

---

Model/QuoteRepository.php
composer.json

- improved background order processing

Vipps Payment 2.3.13

---

Controller/Payment/Klarna/InitRegular.php
Model/LockManagerInterface.php
Model/ModuleMetadataInterface.php
composer.json

- fixed issue with dependency generations

Fixed di:compile issues

---

Cron/CancelQuoteByAttempts.php
Cron/FetchOrderFromVipps.php
Gateway/Http/Client/Curl.php
Model/ModuleMetadata.php
Model/Quote/CancelFacade.php
composer.json
etc/di.xml

- added request tracking headers
- improved order cancellation flow

Vipps Payment tracking headers support

---

Controller/Payment/Klarna/InitRegular.php

Backport Klarna init from PR #88

Fixed failed Vipps init On Klarna.

---

Controller/Payment/Klarna/InitRegular.php
Model/QuoteManagement.php
Model/QuoteRepository.php
Model/TransactionProcessor.php
Setup/UpgradeSchema.php
composer.json
etc/module.xml

- fixed issue with Express Checkout
- optimisation  for quote search mechanism
- fixed issue with Klarna

VIPPS-368: Fixed issue with Express Checkout

---

Controller/Payment/Fallback.php
Gateway/Validator/AvailabilityValidator.php
Model/TransactionProcessor.php
Observer/OrderPaymentAfter.php
composer.json
etc/adminhtml/system/cancellation.xml
etc/config.xml
etc/frontend/di.xml

Vipps Payment publication 2.4.8
- Restore basket when user cancel payment. Now when user cancel payment on Vipps side the basket restored to previous session.
- Additional configuration section added to enable /disable this feature.

Publication 2.4.8

---

Controller/Payment/Fallback.php
composer.json

- Fixed issue when cart persistent even if settings set to "No"

CGRE-280: Fix issue with persistent cart

---

Model/QuoteRepository.php
Model/TransactionProcessor.php
Observer/CheckoutSubmitAllAfter.php
Observer/CheckoutSubmitBefore.php
composer.json
etc/di.xml
etc/events.xml

- Fixed issue when two orders created based on the same quote (VIPPS-374)

VIPPS-374: Stormberg (Visma M2 merchant)

---

Model/QuoteRepository.php
Model/ResourceModel/Quote.php
Observer/CheckoutSubmitBefore.php
composer.json

- Fixed issue with two orders after Vipps order was cancelled

VIPPS-374: Fixed issue with two orders after order was cancelled

---

Block/Adminhtml/System/Config/TestCredentials.php
Controller/Adminhtml/System/Config/TestCredentials.php
Controller/Payment/Fallback.php
Model/TokenProvider.php
Model/TransactionProcessor.php
composer.json
etc/adminhtml/system.xml
view/adminhtml/requirejs-config.js
view/adminhtml/templates/system/config/testcredentials.phtml
view/adminhtml/web/js/testcredentials.js

- Added "Test connection" button in admin panel to check Vipps credentials during configuration
- Fixed an issue when order cancelled with status "Payment Review" (Previously order was not cancelled in Magento)

Publication 2.4

---

Cron/CancelQuoteByAttempts.php
Cron/FetchOrderFromVipps.php
Gateway/Http/Client/Curl.php
Model/ModuleMetadata.php
Model/Quote/CancelFacade.php
composer.json
etc/di.xml

- Vipps Payment tracking headers support (backport, #86)

VIPPS-384: Backport headers to both 2.2 and 2.3

---

Api/QuoteRepositoryInterface.php
Controller/Payment/Fallback.php
Model/Quote/CancelFacade.php
Model/QuoteRepository.php
Model/ResourceModel/Quote.php
Model/TransactionProcessor.php
composer.json

- Fixed an issue with duplicate orders in Magento

VIPPS-385: Duplicate and missing order issue

---

Model/TransactionProcessor.php
composer.json
etc/module.xml

Fixed an issue when cancel order that has been already cancelled

VIPPS-391: State vs status for cancelled orders

---

i18n/nb_NO.csv

Added translation for method description in KCO.

---

composer.json
etc/module.xml
i18n/nb_NO.csv
view/frontend/web/css/vipps_styles.css
view/frontend/web/template/payment/vipps.html

- Added text hind on checkout page (VIPPS-407)

Publication v 2.4.26

---

Gateway/Request/SendReceipt/OrderLinesBuilder.php
composer.json
etc/module.xml

- Add receipts to Vipps after order placed (support for composite product type)

Publication 2.4.33

---

Model/QuoteLocator.php
composer.json
etc/module.xml

- Improved performance of shipping information loading (express checkout)
- Fixed an issue with Php 8.1 compatibility (express checkout)

VIPPS-417: Improve performance of GetShippingDetails service

---

Model/QuoteLocator.php
composer.json
etc/module.xml

- Added backward compatibility with Magento 2.4.3

VIPPS-417: Added backward compatibility with Magento 2.4.3

---

README.md

Reverts vippsas/vipps-magento#196

Revert "Accessibility: Remove alt for decorative images"
